# -*- coding: utf-8 -*-
"""Techno hack edutech

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xp5e5G4lDpNs83e4_YlgZMme26FKGDSe
"""

def z(a,b):
    return a+b
def y(a,b):
    return a-b
def x(a,b):
    return a*b
def u (a,b):
    if b==0:
        return "Invalid input"
    else:
        return a/b

while True:
    print("operation:")
    print("Enter 'z' for addition")
    print("Enter 'y' for substraction")
    print("Enter 'x' for multiplication")
    print("Enter 'u' for division")
    print("Enter 'Quit' to end the program")

    user_input= input("Enter your choice: ")

    if user_input == "Quit":
        break
    elif user_input in('z','y','x','u'):
        print("let's start Calculations")
        num1=float(input("Enter a value:"))
        num2=float(input("Enter b value:"))

        if user_input == 'z':
            print("Sum of numbers:",z(num1,num2))
        elif user_input == 'y':
            print("Difference of numbers:", y(num1,num2))
        elif user_input == 'x':
            print("Product of  numbers:", x(num1,num2))
        elif user_input == 'u':
            print("Divison of numbers:", u(num1,num2))
        else:
            print("Invalid operator")

class ATM:
    def __init__(self, balance=0):
        self.balance = balance

    def check_balance(self):
        return self.balance

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            return f"Deposited ${amount}. New balance: ${self.balance}"
        else:
            return "Invalid deposit amount. Please enter a positive value."

    def withdraw(self, amount):
        if amount > 0 and amount <= self.balance:
            self.balance -= amount
            return f"Withdraw ${amount}. New balance: ${self.balance}"
        elif amount > self.balance:
            return "Insufficient funds."
        else:
            return "Invalid withdrawal amount. Please enter a positive value."

def main():
    atm = ATM()

    while True:
        print("\nATM Menu:")
        print("1. Check Balance")
        print("2. Deposit Money")
        print("3. Withdraw Money")
        print("4. Exit")

        choice = input("Enter your choice (1/2/3/4): ")

        if choice == '1':
            print(f"Your balance: ${atm.check_balance()}")
        elif choice == '2':
            amount = float(input("Enter the deposit amount: $"))
            print(atm.deposit(amount))
        elif choice == '3':
            amount = float(input("Enter the withdrawal amount: $"))
            print(atm.withdraw(amount))
        elif choice == '4':
            print("Thank you for using the ATM. Goodbye!")
            break
        else:
            print("Invalid choice. Please select a valid option.")

if __name__ == "__main__":
    main()

import random

def get_user_choice():
    user_choice = input("Choose Rock, Paper, or Scissors: ").strip().lower()
    while user_choice not in ["rock", "paper", "scissors"]:
        print("Invalid choice. Please choose Rock, Paper, or Scissors.")
        user_choice = input("Choose Rock, Paper, or Scissors: ").strip().lower()
    return user_choice

def get_computer_choice():
    choices = ["rock", "paper", "scissors"]
    return random.choice(choices)

def determine_winner(user_choice, computer_choice):
    if user_choice == computer_choice:
        return "It's a tie!"
    elif (
        (user_choice == "rock" and computer_choice == "scissors")
        or (user_choice == "paper" and computer_choice == "rock")
        or (user_choice == "scissors" and computer_choice == "paper")
    ):
        return "You win!"
    else:
        return "Computer wins!"

def main():
    print("Welcome to Rock, Paper, Scissors!")

    while True:
        user_choice = get_user_choice()
        computer_choice = get_computer_choice()

        print(f"You chose {user_choice}.")
        print(f"Computer chose {computer_choice}.")

        result = determine_winner(user_choice, computer_choice)
        print(result)

        play_again = input("Do you want to play again? (yes/no): ").strip().lower()
        if play_again != "yes":
            break

    print("Thanks for playing!")

if __name__ == "__main__":
    main()