# -*- coding: utf-8 -*-
"""Techno hack calculater

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xp5e5G4lDpNs83e4_YlgZMme26FKGDSe
"""

def z(a,b):
    return a+b
def y(a,b):
    return a-b
def x(a,b):
    return a*b
def u (a,b):
    if b==0:
        return "Invalid input"
    else:
        return a/b

while True:
    print("operation:")
    print("Enter 'z' for addition")
    print("Enter 'y' for substraction")
    print("Enter 'x' for multiplication")
    print("Enter 'u' for division")
    print("Enter 'Quit' to end the program")

    user_input= input("Enter your choice: ")

    if user_input == "Quit":
        break
    elif user_input in('z','y','x','u'):
        print("let's start Calculations")
        num1=float(input("Enter a value:"))
        num2=float(input("Enter b value:"))

        if user_input == 'z':
            print("Sum of numbers:",z(num1,num2))
        elif user_input == 'y':
            print("Difference of numbers:", y(num1,num2))
        elif user_input == 'x':
            print("Product of  numbers:", x(num1,num2))
        elif user_input == 'u':
            print("Divison of numbers:", u(num1,num2))
        else:
            print("Invalid operator")